BeestjeOpJeFeestje/BeestjeOpJeFeestje/Controllers/AccessoryController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BeestjeOpJeFeestje.Domain;
using BeestjeOpJeFeestje.Domain.Interface_Repositories;
using BeestjeOpJeFeestje.Domain.Models;

namespace BeestjeOpJeFeestje.Controllers
{
    public class AccessoryController : Controller
    {
        private readonly IAccessoryRepository _accessRepo;
        private IBoekingRepository _boekingRepository;
        public AccessoryController(IAccessoryRepository AccessRepo, IBoekingRepository boekingRepository)
        {
            _accessRepo = AccessRepo;
            _boekingRepository = boekingRepository;
        }

        // GET: Accessory
        public ActionResult Index()
        {
            var accessory = _accessRepo.GetAll().Select(a => new AccessoryVM(a));
            return View(accessory.ToList());
        }

        // GET: Accessory/Details/5
        public ActionResult Details(int id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var accessory = new AccessoryVM(_accessRepo.Get(id));
            if (accessory == null) return HttpNotFound();
            return View(accessory);
        }

        // GET: Accessory/Create
        public ActionResult Create()
        {
            ViewBag.BeastID = new SelectList(_accessRepo.ContextDB().Beast, "ID", "Name");
            return View();
        }

        // POST: Accessory/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Price,BeastID")]
            AccessoryVM accessory)
        {
            if (ModelState.IsValid)
            {
                _accessRepo.Add(accessory.Accessory);
                _accessRepo.Complete();
                return RedirectToAction("Index");
            }

            ViewBag.BeastID = new SelectList(_accessRepo.ContextDB().Beast, "ID", "Name", accessory.BeastID);
            return View(accessory);
        }

        // GET: Accessory/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var accessory = new AccessoryVM(_accessRepo.Get(id));
            if (accessory == null) return HttpNotFound();
            ViewBag.BeastID = new SelectList(_accessRepo.ContextDB().Beast, "ID", "Name", accessory.BeastID);
            return View(accessory);
        }

        // POST: Accessory/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Price,BeastID")]
            AccessoryVM accessory)
        {
            if (ModelState.IsValid)
            {
                _accessRepo.UpdateAccessory(accessory);
                _accessRepo.Complete();
                return RedirectToAction("Index");
            }

            ViewBag.BeastID = new SelectList(_accessRepo.ContextDB().Beast, "ID", "Name", accessory.BeastID);
            return View(accessory);
        }

        // GET: Accessory/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var accessory = new AccessoryVM(_accessRepo.Get(id));
            if (accessory == null) return HttpNotFound();
            return View(accessory);
        }

        // POST: Accessory/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var accessory = new AccessoryVM(_accessRepo.Get(id));
            var temp = accessory.Booking;
            foreach (var item in temp)
            {
                item.Accessory.Remove(accessory);
            }
            _boekingRepository.RecalculateTotalPrice(temp);
            _accessRepo.Remove(accessory.Accessory);
            _accessRepo.Complete();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                // lol niks
            }

            base.Dispose(disposing);
        }
    }
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Controllers/BeastController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using BeestjeOpJeFeestje.Domain;
using BeestjeOpJeFeestje.Domain.Interface_Repositories;
using BeestjeOpJeFeestje.Domain.Models;

namespace BeestjeOpJeFeestje.Controllers
{
    public class BeastController : Controller
    {
        private readonly IBeastRepository _beastrepo;
        private IAccessoryRepository _accRepo;
        private IBoekingRepository _boekingRepository;
        public BeastController(IBeastRepository BeastRepo, IAccessoryRepository AccRepo, IBoekingRepository boekingRepository)
        {
            _beastrepo = BeastRepo;
            _accRepo = AccRepo;
            _boekingRepository = boekingRepository;
        }

        // GET: Beast
        public ActionResult Index()
        {
            var beast = _beastrepo.GetAll().Select(b => new BeastVM(b));
            return View(beast.ToList());
        }

        // GET: Beast/Details/5
        public ActionResult Details(int id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var beast = new BeastVM(_beastrepo.Get(id));
            if (beast == null) return HttpNotFound();
            return View(beast);
        }

        // GET: Beast/Create
        public ActionResult Create()
        {
            ViewBag.Type = new SelectList(_beastrepo.ContextDB().Type, "Type1", "Type1");
            return View();
        }

        // POST: Beast/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Type,Price")] BeastVM beast)
        {
            if (ModelState.IsValid)
            {
                _beastrepo.Add(beast.Beast);
                _beastrepo.Complete();
                return RedirectToAction("Index");
            }

            ViewBag.Type = new SelectList(_beastrepo.ContextDB().Type, "Type1", "Type1", beast.Type);
            return View(beast);
        }

        // GET: Beast/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var beast = new BeastVM(_beastrepo.Get(id));
            if (beast == null) return HttpNotFound();
            ViewBag.Type = new SelectList(_beastrepo.ContextDB().Type, "Type1", "Type1", beast.Type);
            return View(beast);
        }

        // POST: Beast/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Type,Price")] BeastVM beast)
        {
            if (ModelState.IsValid)
            {
                _beastrepo.UpdateBeast(beast);
                _beastrepo.Complete();
                return RedirectToAction("Index");
            }

            ViewBag.Type = new SelectList(_beastrepo.ContextDB().Type, "Type1", "Type1", beast.Type);
            return View(beast);
        }

        // GET: Beast/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var beast = new BeastVM(_beastrepo.Get(id));
            if (beast == null) return HttpNotFound();
            return View(beast);
        }

        // POST: Beast/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var beast = new BeastVM(_beastrepo.Get(id));
            _accRepo.RemoveRange(beast.Accessory);
            beast.Accessory.Clear();
            _accRepo.Complete();
            var temp = beast.Booking;
            foreach (var item in temp)
            {
                item.Beast.Remove(beast);
            }
            _boekingRepository.RecalculateTotalPrice(temp);
            _beastrepo.Remove(beast.Beast);
            _beastrepo.Complete();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
            }

            base.Dispose(disposing);
        }
    }
}

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Views/Shared/InfoBar.cshtml
@model BeestjeOpJeFeestje.Domain.Models.BookingVM
@{
    Layout = null;
}
<div class="container" style="width: 450px">
    <h3>Bookings overzicht</h3>
    <p>Datum:</p>
    <p>@Model.Date</p>
    <p>Beesten:</p>
    <div class="row">
        <div class="col-lg-4">
            @foreach (var beast in Model.Beast)
            {
                <div class="col-lg-6">
                    <p> @beast.Name </p>
                    <img src="~/Images/@beast.ImagePath" alt="animal" width="50" height="50" />
                </div>
            }
        </div>
    </div>
    <br/>
    <p>Accessoires:</p>
    <ul>
        @foreach (var acc in Model.Accessory)
        {
            <li>@acc.Name</li>
        }
    </ul>
</div>

BeestjeOpJeFeestje/BeestjeOpJeFeestje/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("BOEF", "Index", "Home", new {area = ""}, new {@class = "navbar-brand"})
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Beast CRUD", "Index", "Beast")</li>
                <li>@Html.ActionLink("Accessory CRUD", "Index", "Accessory")</li>
                <li>@Html.ActionLink("Booking CRUD", "Index", "Booking")</li>
            </ul>
        </div>
    </div>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.Year Avans Hogeschool | Kenneth Gerrits en Niels Smits</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", false)
</body>
</html>